numero = int(input("Digite o número cuja tabuada você deseja gerar: "))

print(f"{1} x {numero} = {1 * numero}")
print(f"{1} x {numero} = {2 * numero}")
print(f"{1} x {numero} = {3 * numero}")
print(f"{1} x {numero} = {4 * numero}")
print(f"{1} x {numero} = {5 * numero}")
print(f"{1} x {numero} = {6 * numero}")
print(f"{1} x {numero} = {7 * numero}")
print(f"{1} x {numero} = {8 * numero}")
print(f"{1} x {numero} = {9 * numero}")
print(f"{1} x {numero} = {10 * numero}")
